Add fixes and impovments

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,8 +1,7 @@
-name: Build and deploy tests
+name: Build and deploy
 on:
   pull_request:
-    branches:
-      - master
+    branches: [master]
 
 jobs:
   deploy:
@@ -29,39 +28,48 @@ jobs:
           MYSQL_PASSWORD: institute
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
       - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v2.3.1
         with:
-          java-version: 1.8
+          distribution: 'adopt'
+          java-version: '8.0.332+9'
           architecture: x64
 
       - name: Cache Maven packages
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
 
-      - name: Build and Test with default (JPA) profile
-        run: mvn -B package
+      - name: Build project
+        run: mvn -B package -P JDBC_MySQL
 
       - name: Copy to webapps folder
         run: |
           sudo cp -f /home/runner/work/Students-WebApp/Students-WebApp/target/Students-WebApp.war /host/webapps
-          echo "Timeout for 40 sec (app must deploy on Tomcat during this time)"
-          sleep 40
+          if [ -f /host/webapps/Students-WebApp.war ]
+          then
+            echo "File copied to /host/webapps"
+          else
+            echo "File not copied to /host/webapps"
+            exit 1
+          fi
+          echo "Timeout for 10 sec (app must deploy on Tomcat during this time)"
+          sleep 10
 
       - name: Webapp deploy test
         run: |
           HTTP_CODE=$(curl http://localhost:8282/Students-WebApp/students -s -o /dev/null -I -w "%{http_code}")
           if [[ $HTTP_CODE -eq 200 ]]
           then
-            echo "Success"
+            echo "Success. http_code: $HTTP_CODE"
           else
-            echo "Fail"
+            echo "Fail. http_code: $HTTP_CODE"
             exit 1
           fi
